gen:
	@protoc \
		--proto_path=protobuf "protobuf/orders.proto" \
		--go_out=src/genproto/orders --go_opt=paths=source_relative \
  	--go-grpc_out=src/genproto/orders --go-grpc_opt=paths=source_relative